git:
  depth: 10
notifications:
  email: false

before_install:
  - export BOTO_CONFIG=/dev/null

language: node_js
node_js:
  - "4"
  - osx
env:
  - TARGET_ARCH=x64
osx_image: xcode9.2

script: './script/cibuild'

branches:
  only:
    - master
